#Requires AutoHotkey v2.0

; ▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰
; ZONE CONFIGURATION FILE
; ----------------------------------------------------------------------------------------
; This file is used to map all games ZONE number to ZONE zoneNames.
; ▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰


; ▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰
; ZONE PROPERTIES
; ▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰

global ZONE_MAP := Map(

    ; World 1: Spawn World
    1, Map("zoneName", "Spawn"), 
    2, Map("zoneName", "Colorful Forest"),
    3, Map("zoneName", "Castle"),
    4, Map("zoneName", "Green Forest"),
    5, Map("zoneName", "Autumn"),
    6, Map("zoneName", "Cherry Blossom"),
    7, Map("zoneName", "Farm"),
    8, Map("zoneName", "Backyard"),
    9, Map("zoneName", "Misty Falls"),
    10, Map("zoneName", "Mine"),
    11, Map("zoneName", "Chrystal Caverns"),
    12, Map("zoneName", "Dead Forest"),
    13, Map("zoneName", "Dark Forest"),
    14, Map("zoneName", "Mushroom Field"),
    15, Map("zoneName", "Enchanted Forest"),
    16, Map("zoneName", "Crimson Forest"),
    17, Map("zoneName", "Jungle"),
    18, Map("zoneName", "Jungle Temple"),   
    19, Map("zoneName", "Oasis"),
    20, Map("zoneName", "Beach"),
    21, Map("zoneName", "Coral Reef"),
    22, Map("zoneName", "Shipwreck"),
    23, Map("zoneName", "Atlantis"),
    24, Map("zoneName", "Palm Beach"),
    25, Map("zoneName", "Tiki"),
    26, Map("zoneName", "Pirate Cove"),
    27, Map("zoneName", "Pirate Tavern"),
    28, Map("zoneName", "Shanty Town"),
    29, Map("zoneName", "Desert Village"),
    30, Map("zoneName", "Fossil Digsite"),
    31, Map("zoneName", "Desert Pyramids"),
    32, Map("zoneName", "Red Desert"),
    33, Map("zoneName", "Wild West"),
    34, Map("zoneName", "Grand Canyons"),
    35, Map("zoneName", "Safari"),
    36, Map("zoneName", "Mountains"),
    37, Map("zoneName", "Snow Village"),
    38, Map("zoneName", "Icy Peaks"),
    39, Map("zoneName", "Ice Rink"),
    40, Map("zoneName", "Ski Town"),
    41, Map("zoneName", "Hot Springs"),
    42, Map("zoneName", "Fire and Ice"),
    43, Map("zoneName", "Volcano"),
    44, Map("zoneName", "Obsidian Cave"),
    45, Map("zoneName", "Lava Forest"),
    46, Map("zoneName", "Underworld"),
    47, Map("zoneName", "Underworld Bridge"),
    48, Map("zoneName", "Underworld Castle"),
    49, Map("zoneName", "Metal Dojo"),
    50, Map("zoneName", "Fire Dojo"),
    51, Map("zoneName", "Samurai Village"),
    52, Map("zoneName", "Bamboo Forest"),
    53, Map("zoneName", "Zen Garden"),
    54, Map("zoneName", "Flower Field"),
    55, Map("zoneName", "Fairytale Meadows"),
    56, Map("zoneName", "Fairytale Castle"),
    57, Map("zoneName", "Royal Kingdom"),
    58, Map("zoneName", "Fairy Castle"),
    59, Map("zoneName", "Cozy Village"),
    60, Map("zoneName", "Rainbow River"),
    61, Map("zoneName", "Colorful Mines"),
    62, Map("zoneName", "Colorful Mountains"),
    63, Map("zoneName", "Frost Mountains"),
    64, Map("zoneName", "Ice Sculptures"),
    65, Map("zoneName", "Snowman Town"),
    66, Map("zoneName", "Ice Castle"),
    67, Map("zoneName", "Polar Express"),
    68, Map("zoneName", "Firefly Cold Forest"),
    69, Map("zoneName", "Golden Road"),
    70, Map("zoneName", "No Path Forest"),
    71, Map("zoneName", "Ancient Ruins"),
    72, Map("zoneName", "Runic Altar"),
    73, Map("zoneName", "Wizard Tower"),
    74, Map("zoneName", "Witch Marsh"),
    75, Map("zoneName", "Haunted Forest"),
    76, Map("zoneName", "Haunted Graveyard"),
    77, Map("zoneName", "Haunted Mansion"),
    78, Map("zoneName", "Dungeon Entrance"),
    79, Map("zoneName", "Dungeon"),
    80, Map("zoneName", "Treasure Dungeon"),
    81, Map("zoneName", "Empyrean Dungeon"),
    82, Map("zoneName", "Mythic Dungeon"),
    83, Map("zoneName", "Cotton Candy Forest"),
    84, Map("zoneName", "Gummy Forest"),
    85, Map("zoneName", "Chocolate Waterfall"),
    86, Map("zoneName", "Sweets"),
    87, Map("zoneName", "Toys and Blocks"),
    88, Map("zoneName", "Carnival"),
    89, Map("zoneName", "Theme Park"),
    90, Map("zoneName", "Clouds"),
    91, Map("zoneName", "Cloud Garden"),
    92, Map("zoneName", "Cloud Forest"),
    93, Map("zoneName", "Cloud Houses"),
    94, Map("zoneName", "Cloud Palace"),
    95, Map("zoneName", "Heaven Gates"),
    96, Map("zoneName", "Heaven"),
    97, Map("zoneName", "Heaven Gate Castle"),
    98, Map("zoneName", "Colorful Clouds"),
    99, Map("zoneName", "Rainbow Road"),

    ; World 2: Tech World
    100, Map("zoneName", "Tech Spawn"),
    101, Map("zoneName", "Futuristic City"),
    102, Map("zoneName", "Hologram Forest"),
    103, Map("zoneName", "Robot Farm"),
    104, Map("zoneName", "Bit Stream"),
    105, Map("zoneName", "Neon Mine"),
    106, Map("zoneName", "Mushroom Lab"),
    107, Map("zoneName", "Virtual Garden"),
    108, Map("zoneName", "Data Tree Farm"),
    109, Map("zoneName", "Tech Jungle"),
    110, Map("zoneName", "Lava Jungle"),
    111, Map("zoneName", "Oasis Ruins"),
    112, Map("zoneName", "Future Beach"),
    113, Map("zoneName", "Tech Reef"),
    114, Map("zoneName", "Robo Pirates"),
    115, Map("zoneName", "Cyber Cove"),
    116, Map("zoneName", "Ruinic Desert"),
    117, Map("zoneName", "Charged Pyramids"),
    118, Map("zoneName", "Fallout Desert"),
    119, Map("zoneName", "Tech Wild West"),
    120, Map("zoneName", "Cuboid Canyon"),
    121, Map("zoneName", "Frozen Mountains"),
    122, Map("zoneName", "Frostbyte Forest"),
    123, Map("zoneName", "Forcefield Mine"),
    124, Map("zoneName", "Cyber Base Camp"),
    126, Map("zoneName", "Cracked Iceberg"),
    127, Map("zoneName", "Melted River"),
    128, Map("zoneName", "Nexus"),
    129, Map("zoneName", "Secure Coast"),
    130, Map("zoneName", "Nuclear Forest"),
    131, Map("zoneName", "Radiation Mine"),
    132, Map("zoneName", "Exploded Reactor"),
    133, Map("zoneName", "Spaceship Dock"),
    134, Map("zoneName", "Rocket Planet"),
    135, Map("zoneName", "Lunar Planet"),
    136, Map("zoneName", "Mars Planet"),
    137, Map("zoneName", "Saturn Planet"),
    138, Map("zoneName", "Comet Planet"),
    139, Map("zoneName", "Galaxy Port"),
    140, Map("zoneName", "Electric Garden"),
    141, Map("zoneName", "Mutated Forest"),
    142, Map("zoneName", "Neon City"),
    143, Map("zoneName", "Arcade Town"),
    144, Map("zoneName", "Robot Factory"),
    145, Map("zoneName", "Egg Incubator"),
    146, Map("zoneName", "Hi-Tech Hive"),
    147, Map("zoneName", "Spore Garden"),
    148, Map("zoneName", "UFO Forest"),
    149, Map("zoneName", "Alien Lab"),
    150, Map("zoneName", "Alien Mothership"),
    151, Map("zoneName", "Space Forge"),
    152, Map("zoneName", "Space Factory"),
    153, Map("zoneName", "Space Junkyard"),
    154, Map("zoneName", "Steampunk Alley"),
    155, Map("zoneName", "Steampunk Town"),
    156, Map("zoneName", "Steampunk Clockwork"),
    157, Map("zoneName", "Steampunk Airship"),
    158, Map("zoneName", "Circuit Board"),
    159, Map("zoneName", "Mothership Circuit Board"),
    160, Map("zoneName", "Wizard Ruins"),
    161, Map("zoneName", "Wizard Forest"),
    162, Map("zoneName", "Wizard Tech Forest"),
    163, Map("zoneName", "Wizard Tech Tower"),
    164, Map("zoneName", "Wizard Dungeon"),
    165, Map("zoneName", "Cyberpunk Undercity"),
    166, Map("zoneName", "Cyberpunk Industrial"),
    167, Map("zoneName", "Cyberpunk City"),
    168, Map("zoneName", "Cyberpunk Road"),
    169, Map("zoneName", "Tech Ninja Kyoto"),
    170, Map("zoneName", "Tech Samurai"),
    171, Map("zoneName", "Tech Ninja Village"),
    172, Map("zoneName", "Tech Ninja City"),
    173, Map("zoneName", "Dominus Dungeon"),
    174, Map("zoneName", "Dominus Vault"),
    175, Map("zoneName", "Dominus Lair"),
    176, Map("zoneName", "Holographic Powerplant"),
    177, Map("zoneName", "Holographic City"),
    178, Map("zoneName", "Holographic Forest"),
    179, Map("zoneName", "Holographic Mine"),
    180, Map("zoneName", "Dark Tech Cove"),
    181, Map("zoneName", "Dark Tech Ruins"),
    182, Map("zoneName", "Dark Tech Castle"),
    183, Map("zoneName", "Dark Tech Dungeon"),
    184, Map("zoneName", "Dark Tech Forest"),
    185, Map("zoneName", "Hacker Powerplant"),
    186, Map("zoneName", "Hacker Compound"),
    187, Map("zoneName", "Hacker Base"),
    188, Map("zoneName", "Hacker Error"),
    189, Map("zoneName", "Glitch Forest"),
    190, Map("zoneName", "Glitch City"),
    191, Map("zoneName", "Glitch Skyscrapers"),
    192, Map("zoneName", "Glitch Town"),
    193, Map("zoneName", "Glitch Quantum"),
    194, Map("zoneName", "Quantum Forest"),
    195, Map("zoneName", "Quantum Space Base"),
    196, Map("zoneName", "Quantum Galaxy"),
    197, Map("zoneName", "Void Atomic"),
    198, Map("zoneName", "Void Fracture"),
    199, Map("zoneName", "Void Spiral"),

    ; World 3: Void World
    200, Map("zoneName", "Prison Tower"),
    201, Map("zoneName", "Prison Block"),
    202, Map("zoneName", "Prison Cafeteria"),
    203, Map("zoneName", "Prison Yard"),
    204, Map("zoneName", "Prison HQ"),
    205, Map("zoneName", "Beach Island"),
    206, Map("zoneName", "Ocean Island"),
    207, Map("zoneName", "Tiki Island"),
    208, Map("zoneName", "Jungle Island"),
    209, Map("zoneName", "Volcano Island"),
    210, Map("zoneName", "Hacker Matrix"),
    211, Map("zoneName", "Hacker Fortress"),
    212, Map("zoneName", "Hacker Cave"),
    213, Map("zoneName", "Hacker Lab"),
    214, Map("zoneName", "Hacker Mainframe"),
    215, Map("zoneName", "Dirt Village"),
    216, Map("zoneName", "Stone Forts"),
    217, Map("zoneName", "Silver City"),
    218, Map("zoneName", "Golden Metropolis"),
    219, Map("zoneName", "Diamond Mega City"),
    220, Map("zoneName", "Kawaii Tokyo"),
    221, Map("zoneName", "Kawaii Village"),
    222, Map("zoneName", "Kawaii Grove"),
    223, Map("zoneName", "Kawaii Dreamland"),
    224, Map("zoneName", "Kawaii Temple"),
    225, Map("zoneName", "Grassy Plains"),
    226, Map("zoneName", "Rocky Ridge"),
    227, Map("zoneName", "Crystal Lake"),
    228, Map("zoneName", "Electro Forge"),
    229, Map("zoneName", "Elemental Realm", "pathToCentre", [["d", 775]], "pathToEgg", [["d", 775], ["w", 725]], "pathIntoZone", [["s", 325]], "pathAwayFromEgg", [["s", 1000]], "pathBackToEgg", [["w", 1325]]),
    230, Map("zoneName", "Elysium Fields"),
    231, Map("zoneName", "Ocean Paradise"),
    232, Map("zoneName", "Lost Library"),
    233, Map("zoneName", "Nebula Forest"),
    234, Map("zoneName", "Aether Colosseum", "pathToCentre", [["d", 775]], "pathToEgg", [["d", 775], ["w", 725]], "pathIntoZone", [["s", 325]], "pathAwayFromEgg", [["s", 1000]], "pathBackToEgg", [["w", 1325]]),
    235, Map("zoneName", "Doodle Meadow"),
    236, Map("zoneName", "Doodle Safari"),
    237, Map("zoneName", "Doodle Fairyland"),
    238, Map("zoneName", "Doodle Cave"),
    239, Map("zoneName", "Doodle Oasis", "pathToCentre", [["d", 775]], "pathToEgg", [["d", 775], ["w", 725]], "pathIntoZone", [["s", 325]], "pathAwayFromEgg", [["a", 1500]], "pathBackToEgg", [["w", 1325]]),
    240, Map("zoneName", "Fantasy Spawn", "buttonOffset", -100),
    241, Map("zoneName", "Flora Falls", "buttonOffset", -100),
    242, Map("zoneName", "Lantern Forest", "buttonOffset", -100),
    243, Map("zoneName", "Honeycomb Hollow", "buttonOffset", -100),
    244, Map("zoneName", "Fairy Glade", "buttonOffset", -100),
    245, Map("zoneName", "Windmill Point", "buttonOffset", -100),
    246, Map("zoneName", "Radiant Runestones", "buttonOffset", -100),
    247, Map("zoneName", "Fogbound Forest", "buttonOffset", -100),
    248, Map("zoneName", "Rune Graveyard", "buttonOffset", -100),
    249, Map("zoneName", "Halo Spires", "pathToCentre", [["w", 650], ["d", 400]], "pathToEgg", [["a", 610], ["w", 406]], "pathIntoZone", [["d", 250]], "pathAwayFromEgg", [["s", 1500]], "pathBackToEgg", [["a", 250]], "buttonOffset", -100),
)